#!/usr/bin/env bash

line=$(pidof hl2_linux)
arr=($line)
inst=$1
if [ $# == 0 ]; then
  inst=0
fi

if [ ${#arr[@]} == 0 ]; then
  echo TF2 isn\'t running!
  exit 1
fi

if [ $inst -gt ${#arr[@]} ] || [ $inst == ${#arr[@]} ]; then
  echo wrong index!
  exit 1
fi

proc=${arr[$inst]}

echo Running instances: "${arr[@]}"
echo Attaching to "$proc"

sudo ./detach $inst libnekohook.so

echo loading "$(realpath libnekohook.so)" to "$proc"
sudo gdb -n \
  -ex "attach $proc" \
  -ex "set \$dlopen = (void*(*)(char*, int)) dlopen" \
  -ex "call \$dlopen(\"$(realpath libnekohook.so)\", 1)" \
  -ex "call dlerror()" \
  -ex 'print (char *) $2' \
#  -ex "continue" \
#  -ex "backtrace"
